name: Ads
version: '${project.version}'
main: com.moddedverse.ads.Main
api-version: '1.20'
authors: [Lehtinenkaali]
commands:
  startAds:
    description: startAd command
    usage: /<command>
    aliases: [ads]
  reloadConfig:
    description: reloadAd command
    usage: /<command>
    aliases: [reloadAds]
  stopAds:
    description: stopAd command
    usage: /<command>

