name: Ads
version: '1.0-SNAPSHOT'
main: com.moddedverse.ads.Main
api-version: '1.20'
authors: [ModdedVerse]
commands:
  startAds:
    description: startAd command
    usage: /<command>
    aliases: [ads]
  reloadConfig:
    description: reloadAd command
    usage: /<command>
    aliases: [reloadads]
  stopAds:
    description: stopAd command
    usage: /<command>

